project:
  type: website
  output-dir: docs

website:
  title: "Introduction to Open Science"
  site-url: "https://hu-open-sci.github.io/template/"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: syllabus.qmd
        text: "Syllabus"
      - href: modules.qmd
        text: "Module Overviews"
      - href: assignments.qmd
        text: "Assignments"
      - text: "Rubrics"
        menu: 
          - href: rubrics/lab-rubric.qmd
            text: "Rubric for labs"
          - href: rubrics/final-project-rubric.qmd
            text: "Final project rubric"
      - text: "Modules"
        menu:
          - href: modules/module1.qmd
            text: "Module 1"
          - href: modules/module2.qmd
            text: "Module 2"
          - href: modules/module3.qmd
            text: "Module 3"
          - href: modules/module4.qmd
            text: "Module 4"
    right:
      - icon: github
        href: https://github.com/hu-open-sci
        text: "GitHub"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2

execute:
  echo: false

